spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/logintemplate
  data:
    redis:
      port: '6379'
      host: localhost
  application:
    name: JwtTemplate
  jpa:
    hibernate:
      ddl-auto: update
