spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/logintemplate
  data:
    redis:
      port: '6379'
      host: localhost
  application:
    name: JwtTemplate
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: koreamaximus@gmail.com
    password: wxjl kvma hzsv pzgc
    properties:
      mail.smtp.debug: true
      mail.smtp.connectiontimeout: 1000
      mail.starttls.enable: true
      mail.smtp.auth: true